import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const names=['','虛實','慢框','融景','展翅觀海'];
const descriptions=['','保留紅磚 L 型建築，挑出式格柵長廊連接水池與戶外停留空間。','海側無邊水池與陸側泳池形成兩個水院，步行動線繞水連接咖啡館。','折線石庭、種植島與木平台，形成沒有水池的戶外咖啡花園。','雙翼肋骨屋頂面向海岸，曲線步道環抱草坪花園與戶外座席。'];
const wrap=$('.viewer'),canvas=$('#canvas'),loading=$('#loading'),text=$('#loading-text');
let renderer,scene,camera,controls,selected=1,currentView='bird',request=0,contextPromise,hasModel=false,cameras=[],animation=null,dirty=true;
const cache=new Map();
const world=p=>new THREE.Vector3(p[0],p[2],-p[1]);
function loadingState(message,error=false){loading.hidden=false;text.textContent=message;loading.classList.toggle('error',error);$('#retry').hidden=!error;}
function invalidate(){dirty=true;}
function frame(){requestAnimationFrame(frame);if(!renderer)return;const moved=controls.update();if(animation){const t=Math.min(1,(performance.now()-animation.start)/650),k=t*t*(3-2*t);camera.position.lerpVectors(animation.eye0,animation.eye,k);controls.target.lerpVectors(animation.target0,animation.target,k);camera.lookAt(controls.target);dirty=true;if(t===1)animation=null;}if(dirty||moved){renderer.render(scene,camera);dirty=false;}}
function resize(){const w=wrap.clientWidth,h=wrap.clientHeight;if(!renderer||!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();invalidate();}
function cameraFor(id,key){const list=cameras.filter(c=>c.option===id),suffix={bird:'Bird_Landscape',front:'Front_Elevation',top:'MLP_Top',arrival:'Bird_Existing_Route'}[key];return suffix?list.find(c=>c.name.endsWith(suffix)):list.filter(c=>c.name.includes('Interior'))[key==='interior2'?1:0];}
function view(key,animate=true){const c=cameraFor(selected,key);if(!c)return;currentView=key;$$('[data-view]').forEach(b=>{b.classList.toggle('chosen',b.dataset.view===key);b.setAttribute('aria-pressed',String(b.dataset.view===key));});const eye=world(c.eye),target=world(c.target);camera.fov=THREE.MathUtils.radToDeg(2*Math.atan(36/(2*(c.lens||35))))/Math.max(camera.aspect,1);camera.fov=THREE.MathUtils.clamp(camera.fov,25,85);camera.updateProjectionMatrix();controls.minDistance=.12;controls.maxDistance=650;controls.maxPolarAngle=Math.PI*.98;if(key==='top'){eye.z+=.02;camera.fov=35;camera.updateProjectionMatrix();}if(animate&&hasModel){animation={eye0:camera.position.clone(),target0:controls.target.clone(),eye,target,start:performance.now()};}else{camera.position.copy(eye);controls.target.copy(target);camera.lookAt(target);controls.update();}invalidate();}
function prepare(root){root.traverse(o=>{if(!o.isMesh)return;const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){m.side=THREE.DoubleSide;if(m.map){m.map.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());}if(m.name==='Water'){m.color.setRGB(.025,.24,.29);m.opacity=.76;}if(m.name==='DarkWater'){m.color.setRGB(.012,.04,.055);m.opacity=.9;}if(m.transparent){m.depthWrite=false;}m.needsUpdate=true;}});return root;}
const draco=new DRACOLoader();draco.setDecoderPath('./vendor/draco/');draco.setWorkerLimit(2);
const loader=new GLTFLoader();loader.setDRACOLoader(draco);
async function model(id,token){if(cache.has(id))return cache.get(id);const promise=loader.loadAsync(`assets/option-${String(id).padStart(2,'0')}.glb`,ev=>{if(token===request&&ev.total)text.textContent=`正在載入方案 ${String(id).padStart(2,'0')} · ${Math.round(ev.loaded/ev.total*100)}%`;}).then(g=>prepare(g.scene)).catch(e=>{cache.delete(id);throw e;});cache.set(id,promise);return promise;}
async function select(id){if(!Number.isInteger(id)||id<1||id>4)throw new Error('方案必須為 1 至 4');const token=++request;selected=id;$$('[data-option]').forEach(b=>{const active=Number(b.dataset.option)===id;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});$('#option-code').textContent=`OPTION ${String(id).padStart(2,'0')}`;$('#option-name').textContent=names[id];$('#description').textContent=descriptions[id];$('#poster').src=`assets/option-${String(id).padStart(2,'0')}.jpg`;loadingState(`正在載入方案 ${String(id).padStart(2,'0')}…`);try{const [root]=await Promise.all([model(id,token),contextPromise]);if(token!==request)return;scene.children.filter(o=>o.userData.option).forEach(o=>{o.visible=false;});if(!root.parent){root.userData.option=id;scene.add(root);}root.visible=true;if(!hasModel||!$('#retain').checked)view(currentView,false);hasModel=true;wrap.classList.add('ready');loading.hidden=true;invalidate();return {option:id,name:names[id],view:currentView};}catch(e){if(token===request){loadingState('模型暫時無法載入，請重試。',true);console.error(e);}throw e;}}
async function init(){try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.85;scene=new THREE.Scene();scene.background=new THREE.Color('#beced1');scene.add(new THREE.HemisphereLight(0xe5f4ff,0x827968,1.8));const sun=new THREE.DirectionalLight(0xfff5df,2.2);sun.position.set(-35,65,45);scene.add(sun);const fill=new THREE.DirectionalLight(0xd6eafa,.65);fill.position.set(30,20,-40);scene.add(fill);camera=new THREE.PerspectiveCamera(45,1,.035,1800);controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.09;controls.screenSpacePanning=true;controls.addEventListener('change',invalidate);controls.addEventListener('start',()=>{animation=null;});resize();new ResizeObserver(resize).observe(wrap);cameras=await fetch('assets/cameras.json').then(r=>{if(!r.ok)throw new Error('Camera data unavailable');return r.json();});contextPromise=loader.loadAsync('assets/context.glb').then(g=>{scene.add(prepare(g.scene));invalidate();});frame();await select(1);}catch(e){loadingState(renderer?'模型暫時無法載入，請重試。':'瀏覽器未能啟動 3D，請用支援 WebGL 的瀏覽器開啟。',true);console.error(e);}}
$$('[data-option]').forEach(b=>b.addEventListener('click',()=>select(Number(b.dataset.option)).catch(()=>{})));$$('[data-view]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));$('#reset').addEventListener('click',()=>view('bird'));$('#retry').addEventListener('click',()=>location.reload());$('#fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await wrap.requestFullscreen();}catch{loadingState('此瀏覽器不支援全螢幕，可繼續使用模型。',true);}});canvas.addEventListener('keydown',e=>{const keys={ArrowLeft:-.1,ArrowRight:.1};if(e.key in keys){const offset=camera.position.clone().sub(controls.target);offset.applyAxisAngle(new THREE.Vector3(0,1,0),keys[e.key]);camera.position.copy(controls.target).add(offset);e.preventDefault();invalidate();}else if(e.key==='Home'){view('bird');e.preventDefault();}});
if(document.modelContext?.registerTool){const controller=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'select_design_option',title:'切換咖啡館方案',description:'在 3D 檢視器中顯示指定的咖啡館方案。',inputSchema:{type:'object',properties:{option:{type:'integer',minimum:1,maximum:4}},required:['option'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{if(!input||Object.keys(input).some(k=>k!=='option')||!Number.isInteger(input.option)||input.option<1||input.option>4)throw new Error('Invalid option');if(!renderer||!cameras.length)throw new Error('Viewer is loading');return select(input.option);}},{signal:controller.signal})).catch(()=>{});}catch{}addEventListener('pagehide',()=>controller.abort(),{once:true});}
init();
